Library/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt

app_name = 'library'

urlpatterns = [
    path('', views.listOfBooks, name='home'),
    path('listing/', views.listing, name='listing'),
    path('addbook/', views.AddBook.as_view(), name='addBook'),
    path('<int:pk>/update', views.BooksUpdateView.as_view(), name='books_update'),
    path('<int:pk>/delete', views.BooksDeleteView.as_view(), name='books_delete'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('account/', views.userAccount, name='account'),
    #path('password_change/', auth_views.PasswordChangeView.as_view(template_name='Library/password_change.html', success_url=reverse_lazy('account')), name='password_change')
    path('password_change/', views.ChangePasswordView.as_view(), name='password_change'),
    path('email_change/', views.emailChange, name='email_change'),
    path('firstname_change/', views.firstNameChange, name='firstname_change'),
    path('validate-username/', csrf_exempt(views.UsernameValidationView.as_view()), name='validate-username'),
    path('validate-email/', csrf_exempt(views.EmailValidationView.as_view()), name='validate-email'),
    path('validate-password1/', csrf_exempt(views.PasswordValidationView.as_view()), name='validate-password1')
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Library.urls')),
    path('cart/', include('shopping_cart.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopping_cart/urls.py
#from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/<int:object_id>/', views.add_to_cart, name="add_to_cart"),
    path('order-summary/', views.order_details, name="order_summary"),
    path('success/', views.success, name='purchase_success'),
    path('item/delete/<int:item_id>/', views.delete_from_cart, name='delete_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('update-transaction/<order_id>/', views.update_transaction_records, name='update_records'),
    path('all-orders/', views.all_orders, name='all_orders')
]

Library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db.models.signals import post_save

class Books(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор записи', blank=True, null=True)
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.IntegerField()

    def __str__(self):
        return f'Название книги: {self.name}'

    def get_absolute_url(self):
        return f'/'

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(Books, blank=True)

    def __str__(self):
        return self.user.username


def post_save_profile_create(sender, instance, created, *args, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)

post_save.connect(post_save_profile_create, sender=User)

Library/forms.py
from .models import Books
from django.forms import ModelForm, TextInput, NumberInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class BooksForm(ModelForm):
    class Meta:
        model = Books
        fields = ['name', 'author', 'price']

        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Название книги"
            }),
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Автор книги"
            }),
            'price': NumberInput(attrs={
                'class': 'form-control',
                'placeholder': "Цена книги",
            })
        }


class UserRegisterForm(UserCreationForm, ModelForm):
    username = forms.CharField(label='Никнейм', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'usernameField'},))
    password1 = forms.CharField(min_length=8, label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password1Field'},))
    password2 = forms.CharField(min_length=8, label='Подтверждение пароля', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password2Field'},))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control', 'id': 'emailField'},))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'firstnameField'},))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email', 'first_name')

    def clean(self):
        cleaned_data = super().clean()
        if User.objects.filter(email=cleaned_data.get('email')).exists():
            self.add_error('email', 'Пользователь с данной почтой уже зарегестрирован')
        return cleaned_data


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Никнейм', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class EmailChangeForm(forms.ModelForm):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'},))

    class Meta:
        model = User
        fields = ('email', )

    def clean(self):
        cleaned_data = super().clean()
        if User.objects.filter(email=cleaned_data.get('email')).exists():
            self.add_error('email', 'Пользователь с данной почтой уже зарегестрирован')
        return cleaned_data


class FirstNameChangeForm(forms.ModelForm):
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'},))

    class Meta:
        model = User
        fields = ('first_name', )

Library/views.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from .models import Books, Profile
from .forms import BooksForm, UserRegisterForm, UserLoginForm, EmailChangeForm, FirstNameChangeForm
from django.views.generic import UpdateView, DeleteView, CreateView, View
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from shopping_cart.models import Order
import json
from django.http import JsonResponse
from validate_email import validate_email
from password_validator import PasswordValidator
from .filters import ListingFilter


class UsernameValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        username = data['username']
        if User.objects.filter(username = username).exists():
            return JsonResponse({'username_error': 'Пользователь с таким никнеймом уже существует'}, status = 409)
        return JsonResponse({'username_valid': True})


class EmailValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        email = data['email']
        if not validate_email(email):
            return JsonResponse({'email_error': 'Email не действителен'}, status=409)
        if User.objects.filter(email = email).exists():
            return JsonResponse({'email_error': 'Пользователь с таким email уже существует'}, status = 409)
        return JsonResponse({'email_valid': True})


class PasswordValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        password = data['password1']
        shema = PasswordValidator()
        shema.min(8)
        shema.max(20)
        shema.has().digits()
        shema.has().no().spaces()
        shema.has().symbols()
        if not shema.validate(password):
            return JsonResponse({'password1_error': 'Пароль не корректен'}, status=409)
        return JsonResponse({'password1_valid': True})


def userAccount(request):
    userName = request.user.username
    userEmail = request.user.email
    userFirstName = request.user.first_name
    return render(request, 'Library/user_account.html', {'userName': userName, 'userEmail': userEmail, 'userFirstName': userFirstName})


def listOfBooks(request):
    list = Books.objects.all()
    listing_filter = ListingFilter(request.GET, queryset=list)
    context = {'list': list, 'listing_filter': listing_filter}
    return render(request, 'Library/homePage.html', context)


class CustomSuccessMessageMixin:   #Вывод сообщений об успешном завершении чего-либо
    @property
    def success_msg(self):
        return False

    def form_valid(self, form):
        messages.success(self.request, self.success_msg)
        return super().form_valid(form)


class AddBook(LoginRequiredMixin, CustomSuccessMessageMixin, CreateView): #LoginRequiredMixin обязательно должен быть в крайнем левом положении при наследовании
    login_url = 'library:login'   #Для LoginRequiredMixin, куда перенаправлять не авторизированного пользователя
    redirect_field_name = 'library:login'   #Для LoginRequiredMixin, та же хрень
    model = Books
    template_name = 'Library/addBook.html'
    form_class = BooksForm
    success_msg = 'Запись создана'
    success_url = reverse_lazy('library:home')

    def form_valid(self, form):  #Нужно для автоматического сохранения автора записи
        self.object = form.save(commit=False)  #Этой строчкой сохраняем экземпляр объекта, но ещё метод сохранения не вызван, то есть в БД не записано, это как раз благодаря commit=False
        self.object.user = self.request.user   #Добавление дополнительного параметра автора записи для self.object
        self.object.save()   #Сохранение в БД
        return super().form_valid(form)


#def addBook(request):
#    if request.method == 'POST': #проверка на метод
#        form = BooksForm(request.POST) #тут будут храниться данные, которые получили от user'а при вводе их в форму
#        if form.is_valid(): #проверка правильно ли заполнены формы user'ом
#            form.save() #сохранение введённых данных user'ом
#            messages.success(request, 'Книга успешно добавлена')
#            return redirect('home') #перенаправление на главную страницу после корректного ввода всех данных
#        else:
#            messages.error(request, 'Ошибка добавления книги')
#    form = BooksForm()
#    data = {
#        'form': form
#    }
#    return render(request, 'Library/addBook.html', data)


class BooksUpdateView(LoginRequiredMixin, CustomSuccessMessageMixin, UpdateView):
    login_url = 'library:login'
    redirect_field_name = 'library:login'
    model = Books
    template_name = 'Library/update.html'
    success_msg = 'Запись отредактирована'
    form_class = BooksForm

    def get_form_kwargs(self):   #Ограничение на изменение записи не администратором
        kwargs = super().get_form_kwargs()
        if not self.request.user.is_superuser:
            return self.handle_no_permission()   #Будет выдавать 403 Forbidden
        return kwargs


class BooksDeleteView(LoginRequiredMixin, CustomSuccessMessageMixin, DeleteView):
    login_url = 'library:login'
    redirect_field_name = 'library:login'
    model = Books
    template_name = 'Library/delete.html'
    success_msg = 'Запись удалена'
    success_url = '/'

    def get_form_kwargs(self):   #Ограничение на удаление записи не администратором
        kwargs = super().get_form_kwargs()
        if not self.request.user.is_superuser:
            return self.handle_no_permission()   #Будет выдавать 403 Forbidden
        return kwargs


def listing(request):
    objects = Books.objects.all()
    paginator = Paginator(objects, 5)
    page_number = request.GET.get('page', 1)
    page_objects = paginator.get_page(page_number)
    context = {'page_obj': page_objects}
    return render(request, 'Library/listing.html', context)


class UserRegisterView(CustomSuccessMessageMixin, CreateView):
    template_name = 'Library/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('library:home')
    success_msg = 'Вы успешно зарегистрировались'

    def form_valid(self, form):    #Автоматическая авторизация после регистрации
        form_valid = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        auth_user = authenticate(username=username, password=password)
        login(self.request, auth_user)
        return form_valid


#def register(request):
#    if request.method == 'POST':
#        form = UserRegisterForm(request.POST)
#        if form.is_valid():
#            user = form.save()
#           login(request, user)
#            messages.success(request, 'Вы успешно зарегистрировались')
#            return redirect('home')
#        else:
#            messages.error(request, 'Ошибка регистрации')
#    form = UserRegisterForm()
#    return render(request, 'Library/register.html', {'form': form})


class UserLoginView(CustomSuccessMessageMixin, LoginView):
    template_name = 'Library/login.html'
    form_class = UserLoginForm
    next_page = reverse_lazy('library:home')
    success_msg = 'Вы успешно авторизовались'

#def user_login(request):
#    if request.method == 'POST':
#        form = UserLoginForm(data=request.POST)
#        if form.is_valid():
#            user = form.get_user()
#            login(request, user)
#            messages.success(request, 'Вы успешно авторизовались')
#            return redirect('home')
#        else:
#            messages.error(request, 'Ошибка авторизации')
#    form = UserLoginForm()
#    return render(request, 'Library/login.html', {"form": form})


class UserLogoutView(CustomSuccessMessageMixin, LogoutView):
    next_page = reverse_lazy('library:home')


#def user_logout(request):
#    logout(request)
#    messages.info(request, 'Вы вышли из учетной записи')
#    return redirect('home')

class ChangePasswordView(CustomSuccessMessageMixin, PasswordChangeView):
    template_name = 'Library/password_change.html'
    success_url = reverse_lazy('library:account')
    success_msg = 'Вы успешно изменили пароль'


def emailChange(request):
    if request.method == 'POST':
        emailChangeForm = EmailChangeForm(request.POST)
        if emailChangeForm.is_valid():
            request.user.email = emailChangeForm.cleaned_data['email']
            request.user.save()
            messages.success(request, F'Вы успешно изменили почту на {emailChangeForm.cleaned_data["email"]}')
            return redirect('library:account')
        else:
            messages.error(request, 'Ошибка изменения почты')
    else:
        emailChangeForm = EmailChangeForm()
    return render(request, 'Library/email_change.html', {'form': emailChangeForm})


def firstNameChange(request):
    if request.method == 'POST':
        firstNameChangeForm = FirstNameChangeForm(request.POST)
        if firstNameChangeForm.is_valid():
            request.user.first_name = firstNameChangeForm.cleaned_data['first_name']
            request.user.save()
            messages.success(request, F'Вы успешно изменили имя на {firstNameChangeForm.cleaned_data["first_name"]}')
            return redirect('library:account')
        else:
            messages.error(request, 'Ошибка изменения имени')
    else:
        firstNameChangeForm = FirstNameChangeForm()
    return render(request, 'Library/firstname_change.html', {'form': firstNameChangeForm})

Library/templates/Library/about.html
{% extends 'Library/standart.html' %}

{% block title %}
Автор книги
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Автор книги</h1>
        <p>Дай Бог всё будет хорошо</p>
        <button class="btn btn-warning">Ещё кнопошка</button>
    </div>
{% endblock %}

Library/templates/Library/addBook.html
{% extends 'Library/standart.html' %}

{% block title %}
Добавление книги
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Добавьте новую книгу в список</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.name }}<br>
            {{ form.author }}<br>
            {{ form.price }}<br>
            <button class="btn btn-success" type="submit">Добавить запись</button>
        </form>
    </div>
{% endblock %}

Library/templates/Library/delete.html
{% extends 'Library/standart.html' %}

{% block title %}
Удаление книги
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Удалите книгу из списка</h1>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-warning" type="submit">Удалить запись</button>
        </form>
    </div>

{% endblock %}

Library/templates/Library/email_change.html
{% extends 'Library/standart.html' %}

{% block title %}
Смена E-Mail
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Смените E-Mail</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }} {{ field }}
                    {% for error in field.errors %}
                        <p style="color: darkred">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <button class="btn btn-success" type="submit">Сменить E-Mail</button>
        </form>
    </div>
{% endblock %}

Library/templates/Library/firstname_change.html
{% extends 'Library/standart.html' %}

{% block title %}
Смена имя
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Смените имя</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }} {{ field }}
                    {% for error in field.errors %}
                        <p style="color: darkred">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <button class="btn btn-success" type="submit">Сменить имя</button>
        </form>
    </div>
{% endblock %}

Library/templates/Library/homePage.html
{% extends 'Library/standart.html' %}

{% block title %}
Главная страница
{% endblock %}

{% block content %}
    <div class="features">
        <h1>Список доступных книг</h1>
        <h6>Здесь вы можете изменить информацию о книге, её авторе и цене. Так же доступны опции удаления записи и добавления новой записи.</h6>
    <form method="get">{{ listing_filter.form.as_p }}<button type="submit" class="btn btn-outline-info btn-sm">Применить фильтры</button></form><br>
        <div class="listOfBooks">
        {% for book in listing_filter.qs %}
            <p>{{ book.name }}, {{ book.author }}, {{ book.price }} руб., запись добавил: {{ book.user }}
                <a href="{% url 'library:books_update' book.id %}"><button type="button" class="btn btn-outline-dark btn-sm">Изменить запись</button></a>
                <a id="{{ book.id }}" href="{% url 'shopping_cart:add_to_cart' book.id %}" class="btn btn-outline-info btn-sm">Добавить_в_корзину</a>
                <a href="{% url 'library:books_delete' book.id %}"><button type="button" class="btn btn-outline-warning btn-sm">Удалить запись</button></a></p>
        {% endfor %}
        </div>
        <a href="{% url 'library:addBook' %}"><button type="button" class="btn btn-success">Добавить новый элемент</button></a>
    </div>
{% endblock %}

Library/templates/Library/index.html
{% extends 'Library/standart.html' %}

{% block title %}
Главная страница
{% endblock %}
{% block content %}
    <div class="features">
        <h1>{{ title }}</h1>
        <p>Вот вроде работает, пока что...</p>
        <button class="btn btn-warning">Кнопошка</button>
        {% for value in values %}
            {% if value != 'test' %}
                <p>{{ value }}</p>
            {% endif %}
        {% endfor %}

    </div>
{% endblock %}

Library/templates/Library/listing.html
{% extends 'Library/standart.html' %}

{% block title %}
Постраничная навигация
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Список доступных книг</h1>
        <h6>Здесь вы можете изменить информацию о книге, её авторе и цене. Так же доступны опции удаления записи и добавления новой записи.</h6>
        {% for book in page_obj  %}
            <p>{{ book.name }}, {{ book.author }}, {{ book.price }} руб.
                <a href="{% url 'library:books_update' book.id %}"><button type="button" class="btn btn-outline-dark btn-sm">Изменить запись</button></a>
                <a href="{% url 'shopping_cart:add_to_cart' book.id %}" class="btn btn-outline-info btn-sm">Добавить в корзину</a>
                <a href="{% url 'library:books_delete' book.id %}"><button type="button" class="btn btn-outline-warning btn-sm">Удалить запись</button></a></p>
        {% endfor %}
        <nav aria-label="...">
            <ul class="pagination justify-content-center">
                {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                        <li class="page-item active"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
    </div>
{% endblock %}

Library/templates/Library/login.html
{% extends 'Library/standart.html' %}

{% block title %}
Авторизация
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Авторизуйтесь на сайте</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }} {{ field }}
                    {% for error in field.errors %}
                        <p style="color: darkred">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <button class="btn btn-success" type="submit">Авторизоваться</button>
        </form>
    </div>
{% endblock %}

Library/templates/Library/password_change.html
{% extends 'Library/standart.html' %}

{% block title %}
Смена пароля
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Смените пароль</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }} {{ field }}
                    {% for error in field.errors %}
                        <p style="color: darkred">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <button class="btn btn-success" type="submit">Сменить пароль</button>
        </form>
    </div>
{% endblock %}

Library/templates/Library/register.html
{% extends 'Library/standart.html' %}
{% load static %}

{% block title %}
Регистрация
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Зарегистрируйтесь на сайте</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }} {{ field }}
                {% if field == form.username %}
                <div class="invalid_feedback invalid-feedback" style="display: none"></div>
                {% endif %}
                {% if field == form.email %}
                <div class="emailFeedBackArea invalid-feedback" style="display: none"></div>
                {% endif %}
                {% if field == form.password1 %}
                <div class="password1FeedBackArea invalid-feedback" style="display: none"></div>
                {% endif %}
                {% if field == form.password2 %}
                <div class="password2FeedBackArea invalid-feedback" style="display: none"></div>
                {% endif %}
                    {% for error in field.errors %}
                        <p style="color: darkred">{{ error }}</p>
                    {% endfor %}
                    {% if field.errors %}
                    <p>field.errors</p>
                    {% endif %}
                </p>
            {% endfor %}
            <button class="btn btn-success" type="submit">Зарегистрироваться</button>
        </form>
    </div>


<script src="{% static 'Library/js/register.js' %}"></script>
{% endblock %}

Library/templates/Library/standart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Library/css/Library.css' %}">
</head>
<body>
    <aside>
        <img src="{% static 'Library/img/boss.jpg' %}" alt="BOSS">
        <span class="logo">Boss</span>
        <h3>Навигация</h3>
        <ul>
            <a href="{% url 'library:home' %}"><li>Все книги</li></a>
            <a href="{% url 'library:listing' %}"><li>Постраничная навигация</li></a>
        </ul>
        <span>
        {% if request.user.is_authenticated %}
            <p style="text-align: center; margin-top: 50px">Добро пожаловать, <a href="{% url 'library:account' %}">{{ user.username }}</a><br><a id="cart_link" href="{% url 'shopping_cart:order_summary' %}">Перейти в корзину</a><br><a id="all_my_orders" href="{% url 'shopping_cart:all_orders' %}">Все мои заказы</a></p>
            <a style="margin-left: 25%" href="{% url 'library:logout' %}">Выход из учётной записи</a>
        {% else %}
            <ul>
                <a id="reg" href="{% url 'library:register' %}"><li>Регистрация</li></a>
                <a id="log" href="{% url 'library:login' %}"><li>Авторизация</li></a>
            </ul>
        {% endif %}
        </span>
    </aside>
    <main>
        <div class="mes">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Library/templates/Library/update.html
{% extends 'Library/standart.html' %}

{% block title %}
Изменение данных о книге
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Измените данные о книге</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.name }}<br>
            {{ form.author }}<br>
            {{ form.price }}<br>
            <span>{{ error }}</span>
            <button class="btn btn-success" type="submit">Сохранить изменения</button>
        </form>
    </div>
{% endblock %}

Library/templates/Library/user_account.html
{% extends 'Library/standart.html' %}

{% block title %}
Аккаунт пользователя
{% endblock %}
{% block content %}
    <div class="features">
        <h1>Аккаунт пользователя</h1>
        <p>Здесь вы можете изменить Ваши пароль, имя, E-Mail,</p>
        <p><b>Ваш ник-нейм:</b> <big>{{ userName }}</big></p>
        <p><b>Ваше имя:</b> <big>{{ userFirstName }}</big></p>
        <p><b>Ваш E-Mail:</b> <big>{{ userEmail }}</big></p>
        <a href="{% url 'library:password_change' %}"><button type="button" class="btn btn-outline-info">Изменить пароль</button></a> <a href="{% url 'library:firstname_change' %}"><button type="button" class="btn btn-outline-info">Изменить имя</button></a> <a href="{% url 'library:email_change' %}"> <button type="button" class="btn btn-outline-info">Изменить E-Mail</button></a>
    </div>

{% endblock %}