Library/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt

app_name = 'library'

urlpatterns = [
    path('', views.listOfBooks, name='home'),
    path('listing/', views.listing, name='listing'),
    path('addbook/', views.AddBook.as_view(), name='addBook'),
    path('<int:pk>/update', views.BooksUpdateView.as_view(), name='books_update'),
    path('<int:pk>/delete', views.BooksDeleteView.as_view(), name='books_delete'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('account/', views.userAccount, name='account'),
    #path('password_change/', auth_views.PasswordChangeView.as_view(template_name='Library/password_change.html', success_url=reverse_lazy('account')), name='password_change')
    path('password_change/', views.ChangePasswordView.as_view(), name='password_change'),
    path('email_change/', views.emailChange, name='email_change'),
    path('firstname_change/', views.firstNameChange, name='firstname_change'),
    path('validate-username/', csrf_exempt(views.UsernameValidationView.as_view()), name='validate-username'),
    path('validate-email/', csrf_exempt(views.EmailValidationView.as_view()), name='validate-email'),
    path('validate-password1/', csrf_exempt(views.PasswordValidationView.as_view()), name='validate-password1')
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Library.urls')),
    path('cart/', include('shopping_cart.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopping_cart/urls.py
#from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/<int:object_id>/', views.add_to_cart, name="add_to_cart"),
    path('order-summary/', views.order_details, name="order_summary"),
    path('success/', views.success, name='purchase_success'),
    path('item/delete/<int:item_id>/', views.delete_from_cart, name='delete_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('update-transaction/<order_id>/', views.update_transaction_records, name='update_records'),
    path('all-orders/', views.all_orders, name='all_orders')
]

shopping_cart/models.py
from django.db import models
from django.contrib.auth.models import User
from Library.models import Profile, Books

class OrderItem(models.Model):
    product = models.OneToOneField(Books, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name

class Order(models.Model):
    ref_code = models.CharField(max_length=20)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

shopping_cart/views.py
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from Library.models import Profile, Books
from shopping_cart.models import OrderItem, Order
from shopping_cart.extras import generate_order_id
####


def get_user_pending_order(request):
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    user_profile = get_object_or_404(Profile, user=request.user)
    product = Books.objects.filter(id=kwargs.get('object_id', "")).first()
    #if product in request.user.profile.books.all():
    #    messages.info(request, 'У вас уже есть эта книга')
    #    return redirect('library:home')
    order_item, status = OrderItem.objects.get_or_create(product=product)
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        user_order.ref_code = generate_order_id()
        user_order.save()

    messages.info(request, "Книга добавлена в корзину")
    return redirect('library:home')


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Выбранная книга удалена из заказа")
    return redirect('shopping_cart:order_summary')


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {'order': existing_order}
    return render(request, 'shopping_cart/order_summary.html', context)


@login_required()
def checkout(request):
    existing_order = get_user_pending_order(request)
    context = {'order': existing_order}
    return render(request, 'shopping_cart/checkout.html', context)


#@login_required()
#def process_payment(request, order_id):
#    return redirect(reverse_lazy('shopping_cart:update_records', kwargs={'order_id': order_id, }))


@login_required()
def update_transaction_records(request, order_id):
    order_to_purchase = Order.objects.filter(pk=order_id).first()
    order_to_purchase.is_ordered = True
    order_to_purchase.date_ordered = datetime.datetime.now()
    order_to_purchase.save()
    order_items = order_to_purchase.items.all()
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())
    user_profile = get_object_or_404(Profile, user=request.user)
    order_products = [item.product for item in order_items]
    user_profile.books.add(*order_products)
    user_profile.save()

    messages.info(request, "Вы совершили покупку")
    return redirect('shopping_cart:purchase_success')


def success(request, **kwargs):
    return render(request, 'shopping_cart/purchase_success.html', {})

def get_user_all_orders(request):
    user_profile = get_object_or_404(Profile, user=request.user)
    allOrdersQuerySet = Order.objects.filter(owner=user_profile, is_ordered=True)
    if allOrdersQuerySet.exists():
        return allOrdersQuerySet
    return 0

def all_orders(request):
    all_existing_orders = get_user_all_orders(request)
    context = {'all_orders': all_existing_orders}
    return render(request, 'shopping_cart/all_orders.html', context)

shopping_cart/templates/shopping_cart/all_orders.html
{% extends 'Library/standart.html' %}

{% block title %}
Все мои заказы
{% endblock %}

{% block content %}
<div class="features">
<h1>Список моих заказов</h1>
<section>
{% if all_orders != 0 %}
    {% for order in all_orders %}
        <table class="table">
            <tr class="text-center">
                <th><h4>Книги</h4></th><th><h4>Цена</h4></th>
            </tr>
            <tr>
                <td>
                    {% for item in order.get_cart_items %}
                        <tr>
                            <td>{{ item }}</td>
                            <td>{{ item.product.price }} руб.</td>
                        </tr>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td><strong>Сумма заказа</strong> </td>
                <td><strong>{{ order.get_cart_total }} руб.</strong></td>
            </tr>
            <tr>
                <td colspan="2">Заказ был совершён {{ order.date_ordered }}</td>
            </tr>
        </table>
    {% endfor %}
{% else %}
<h3>Пока что не было совершено ни одного заказа</h3>
{% endif %}
</section>
</div>
{% endblock content %}

shopping_cart/templates/shopping_cart/checkout.html
{% extends 'Library/standart.html' %}

{% block title %}
Оформление заказа
{% endblock %}

{% block content %}
<div class="features">
<h1>Оформление заказа</h1>
<section>
    <table class="table">
        <tr class="text-center">
            <th><h4>Книги</h4></th><th><h4>Цена</h4></th>
        </tr>
        <tr>
            <td>
                {% for item in order.get_cart_items %}
                    <tr>
                        <td>{{ item }}</td>
                        <td>{{ item.product.price }} руб.</td>
                    </tr>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td><strong>Сумма заказа</strong> </td>
            <td><strong>{{ order.get_cart_total }} руб.</strong></td>
        </tr>
    </table>
    <form method="POST" action="{% url 'shopping_cart:update_records' order.id %}">{% csrf_token %}<button id="update_records" class="btn btn-info">Оплатить заказ</button></form>
</section>
</div>
{% endblock content %}

shopping_cart/templates/shopping_cart/order_summary.html
{% extends "Library/standart.html" %}

{% block title %}
Корзина
{% endblock %}

{% block content %}
<div class="features">
<h1>Ваша корзина</h1>
 <section>
    <table class="table">
      <tr class="text-center">
        <th>Номер</th><th>Книга</th><th>Цена</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.name }}
            <span>
                <font size="1"><a href="{% url 'shopping_cart:delete_item' item.id %}">Удалить книгу</a></font>
            </span>
          </td>
          <td>{{ item.product.price }} руб.</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> Вы не положили ни одной книги в корзину</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong>Цена за всё:</strong>
        </td>
        
        <td colspan= 1>
          <strong>{{ order.get_cart_total }} руб.</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'library:home' %}" class="btn btn-outline-dark pull-left btn-sm">
            {% if order %}Продолжить покупки{% else %}Добавить книги в корзину{% endif %}
          </a> 
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a id="checkout" href="{% url 'shopping_cart:checkout' %}" class="btn btn-outline-primary btn-sm">Перейти к оформлению заказа</a>
          {% endif %}
        </td>
      </tr>
    </table>
 </section>
</div>
{% endblock %}

shopping_cart/templates/shopping_cart/purchase_success.html
{% extends 'Library/standart.html' %}

{% block title %}
Спасибо за покупку!
{% endblock %}

{% block content %}
    <div class="features">
    <h1>Спасибо за покупку!</h1>
        <div class="purchase"><a id="go_home" href="{% url 'library:home' %}">Вернуться на стартовую страницу</a></div>
    </div>
{% endblock content %}